### ISSUE TITLE
Test domain needed

### ISSUE THREAD

**Issue by da2x** [datprotocol/dat-dns#14]
There are no tests for dat key discovery in DNS. We need a subdomain with a datkey and no well-know fallback (no beed for a https server at all).

This should preferably exist under one of the project's official domain names.

**Comment by pfrazee** [comment]
We actually do have that test, see https://github.com/datprotocol/dat-dns/blob/master/test.js#L130. The "noWellknownDat" option forces it to use DNS lookups.

**Comment by pfrazee** [comment]
Ah, you know what? Looks like the DNS tests aren't ignoring the cache and so they're not really testing those pathways. Fixing.

**Comment by pfrazee** [comment]
Okay that's fixed. All set.
