### ISSUE TITLE
Issues with quad9 DoH provider

### ISSUE THREAD

**Issue by pfrazee** [datprotocol/dat-dns#18]
I'm getting some failed lookups from quad9, especially for `unwalled.garden`. I cant find any documentation from them that could explain why that is.

**Comment by da2x** [comment]
What does it return?

**Comment by martinheidegger** [comment]
I had same issue, returning sometimes empty texts or errors. Thus I removed it in https://github.com/datprotocol/dat-dns/commit/b61c47448829da5d48c08c88ff41fd1d16ccd692
