### ISSUE TITLE
Web compatibility regression in 4.0.2

### ISSUE THREAD

**Issue by sammacbeth** [datprotocol/dat-dns#21]
The introduction of [this line](https://github.com/datprotocol/dat-dns/blob/master/cache.js#L109) in the latest version breaks this module on non-node platforms, where the `Timer.unref` function doesn't exist.

**Comment by RangerMauve** [comment]
Oh weird. Mind submitting a PR which makes the `.unref` call optional? I'm not exactly sure what it's there for, even.

**Comment by pfrazee** [comment]
Thanks for the heads up, fixed in `4.0.3`

**Comment by sammacbeth** [comment]
Thanks for the quick fix!
