### ISSUE TITLE
doh (dns over https)

### ISSUE THREAD

**Issue by millette** [datprotocol/dat-dns#4]
FYI: <https://datatracker.ietf.org/wg/doh/about/>

> This working group will standardize encodings for DNS queries and responses
that are suitable for use in HTTPS. This will enable the domain name system to
function over certain paths where existing DNS methods (UDP, TLS [RFC 7857],
and DTLS [RFC 8094]) experience problems.

Draft spec: <https://datatracker.ietf.org/doc/draft-ietf-doh-dns-over-https/>

**Comment by martinheidegger** [comment]
There have been updates to this in the meantime and dat-dns does use dns over https at the moment, so I am closing this issue. Note for the moment: it uses JSON and not dns package API which seems to be only support by google & cloudflare.
