### ISSUE TITLE
Special case: .local domains

### ISSUE THREAD

**Issue by brechtpm** [datprotocol/dat-dns#5]
Currently it's impossible to access dats on a local network using multicasted .local domains. I noticed this when trying to serve dats [from a local Raspberry Pi using `dathttpd`](https://github.com/beakerbrowser/dathttpd/issues/34), and I think supporting this special case is worth considering. Since there's currently no userfriendly way to use SSL with .local domains, the current design basically writes those off altogether. So I propose that for the special case of multicasted domains, we allow `dat-dns` to get its records over plain HTTP.

I guess there's some security issues that we'd have to consider. My feeling is that a user requesting a .local address is already showing a degree of trust in the local network, which makes this less problematic. But I don't know enough about network security to make a fully informed judgement call on this, so I'd be very interested to hear your feedback.

**Comment by pfrazee** [comment]
Hmm, this is interesting.

Basically you're going to be trusting that nobody on the LAN is going to reply "falsely" to a mDNS query, which is trivial to do. All you have to do is tell your mDNS tool "I am now X.local" and then there will be conflicts.

I think the risk is small when used as a tool for people to get their devices in communication. The real risk is that an office or coffee shop might come to depend on `.local` addresses as infrastructure ("Log onto the wifi and visit coffee.local") and then it's trivial to MITM people.

That makes me thing the right strategy is to add support but document the risk. If we develop new methods for authenticating mDNS responses, then we can expand the recommended uses of `.local`.

**Comment by brechtpm** [comment]
Right, as you point out mDNS right now is basically insecure by design. So it could definitely be justified to keep not supporting it for that reason.

If we do want to add support though, I think documenting can only be a first step. We can't expect every user to be familiar with the documentation, so this would only reach developers. They would then have to take the required steps to protect their users of their applications. Taking Beaker as an example, we could use the security area in the URL bar to display a "Local domain" warning similar to the one already in place for plain HTTP.

As I said, I think the decision not to support this would be entirely justifiable. I just think that the use of dat-websites over mDNS could be very powerful, giving you the ability to "take home" any interesting .local site you discover, for example at a meetup or a conference.

**Comment by pfrazee** [comment]
I agree about the "Local domain" warning in apps like Beaker. My thinking is that documentation will be an effective choice if `.local` domains are only special knowledge. I'd hesitate to make .locals common knowledge until we have a good solution for authentication, so though I *love* the idea of using it in conferences and meetups I wonder if we should encourage it, or write software that makes it easy to broadcast .local bindings (ie in Beaker).

I would like to investigate more multicast UDP discovery schemes, too. Might be interesting if folks could simply broadcast their presence, with no name binding (but perhaps name labels). That way you could announce your personal site, for instance.

**Comment by brechtpm** [comment]
Good point, maybe a custom UDP scheme would indeed be better suited for this case. We could basically just (selectively) multicast the contents of `dat.json` over the network to achieve very similar functionality. Might be good to get the input of other people in @dat-land, because applications like `dat-desktop` might want to use the same format.

**Comment by mafintosh** [comment]
Just noting that we never rely on discovery traffic being secure and that
only your discovery key is ever announced.

**Comment by brechtpm** [comment]
Okay, based on the various arguments in this discussion, I think it's probably not a good idea to poke holes into the security model of this package. A tailor made multicast protocol that could be used by higher level applications seems like a better way forward.

Gonna close this issue, but feel free to reopen if you think I'm jumping to conclusions.
